import assert from "node:assert/strict";
import { cp, mkdir, mkdtemp, readFile, rename, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";
import { AGENT_DIR_ENTRY, loadAgentDir } from "../dist/index.js";
import { agentDirRunDefaults, slugifyAgentDirId } from "../dist/dir-loader.js";
import { agentDefinitionSHA256 } from "../dist/build.js";

const TOOL_IMPLEMENTATION_SOURCE = Symbol.for(
  "@caveman-ai/agent:tool-implementation-source",
);
const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const fixtureSource = fileURLToPath(new URL("./fixtures/agent-dir", import.meta.url));

// The committed fixture is copied to a temp directory before loading so the
// generated .caveman/agent-dir-entry.mjs never lands in the repo tree, and a
// node_modules symlink gives the fixture's tools the same bare
// "@caveman-ai/agent" import a scaffolded project has.
async function fixtureCopy(name = "support-mini") {
  const base = await mkdtemp(join(tmpdir(), "cave-agent-dir-"));
  const root = join(base, name);
  await cp(fixtureSource, root, { recursive: true });
  await mkdir(join(root, "node_modules", "@caveman-ai"), { recursive: true });
  await symlink(
    packageRoot,
    join(root, "node_modules", "@caveman-ai", "agent"),
    process.platform === "win32" ? "junction" : "dir",
  );
  return { base, root };
}

test("loadAgentDir lowers a convention directory into one agent()", async () => {
  const { base, root } = await fixtureCopy();
  try {
    const definition = await loadAgentDir(root);
    assert.equal(definition.kind, "agent");
    assert.equal(definition.id, "support-mini");
    assert.equal(
      definition.instructions,
      await readFile(join(root, "instructions.md"), "utf8"),
    );
    assert.equal(definition.model, "anthropic/claude-haiku-4-5");

    // tools/echo_word.ts: filename = tool name, default export is tool().
    const names = definition.tools.map((tool) => tool.name);
    assert.deepEqual(names, ["echo_word", "helper"]);
    const echo = definition.tools[0];
    assert.equal(typeof Reflect.get(echo, TOOL_IMPLEMENTATION_SOURCE), "string");

    // subagents/helper/ recursed with the same loader.
    const helper = definition.tools[1];
    assert.equal(helper.runtime?.kind, "subagent");
    assert.equal(helper.runtime.definition.id, "helper");
    assert.equal(
      helper.runtime.definition.instructions,
      await readFile(join(root, "subagents/helper/instructions.md"), "utf8"),
    );

    // Context stability: bare entries default to "build" (frozen prefix —
    // load-bearing for phase 2's volatile-prefix check); explicit "turn"
    // opts into the live zone.
    const policy = definition.contexts.find((entry) => entry.id === "policy");
    assert.equal(policy.stability, "build");
    assert.equal(policy.cacheRegion, "frozen_prefix");
    assert.equal(policy.source, "Always answer politely.");
    const today = definition.contexts.find((entry) => entry.id === "today");
    assert.equal(today.stability, "turn");
    assert.equal(today.cacheRegion, "live_zone");
    assert.equal(today.source, "turn-scoped value");

    assert.equal(definition.contexts.length, 2);

    // Run defaults from agent.ts, overridable by explicit RunOptions.
    const defaults = agentDirRunDefaults(definition);
    assert.deepEqual(defaults.budget, { maxUsd: 0.05 });
    assert.deepEqual(defaults.breakers, { repeatedToolCalls: 2 });
    assert.equal(defaults.rootDir, root);
    assert.equal(defaults.entryPath, AGENT_DIR_ENTRY);

    // The generated module entry exists, pins the root id, and recomposes
    // through composeAgentDir with static imports only.
    const entry = await readFile(join(root, AGENT_DIR_ENTRY), "utf8");
    assert.match(entry, /GENERATED by @caveman-ai\/agent/);
    assert.match(entry, /composeAgentDir\(/);
    assert.match(entry, /id: "support-mini"/);
    assert.match(entry, /import tool_0_0 from "\.\.\/tools\/echo_word\.ts"/);
    assert.match(entry, /"\.\.\/subagents\/helper\/agent\.ts"/);
    assert.equal(entry.includes("import("), false);
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("the generated entry recomposes the identical definition digest", async () => {
  // This is the required-sandbox contract: the tool worker imports the
  // generated entry from a staged copy and must arrive at the same
  // agent-definition digest the parent composed, or every tool call fails
  // with cave_sandbox_definition_mismatch.
  const { base, root } = await fixtureCopy();
  try {
    const composed = await loadAgentDir(root);
    const imported = await import(
      `${pathToFileURL(join(root, AGENT_DIR_ENTRY)).href}?cave=${Date.now()}`
    );
    assert.equal(
      agentDefinitionSHA256(imported.default),
      agentDefinitionSHA256(composed),
    );
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("tool filename must equal the declared tool name, error names both", async () => {
  const { base, root } = await fixtureCopy();
  try {
    await rename(
      join(root, "tools", "echo_word.ts"),
      join(root, "tools", "wrong_name.ts"),
    );
    await assert.rejects(
      loadAgentDir(root),
      /tools\/wrong_name\.ts declares tool "echo_word"/,
    );
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("a directory without instructions.md fails with a clear error", async () => {
  const { base, root } = await fixtureCopy();
  try {
    await rm(join(root, "instructions.md"));
    await assert.rejects(loadAgentDir(root), /has no instructions\.md/);
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("sibling subagent directories slugging to one id fail closed naming both", async () => {
  const { base, root } = await fixtureCopy();
  try {
    // "helper!" slugs to "helper", colliding with the existing helper/.
    await cp(
      join(root, "subagents", "helper"),
      join(root, "subagents", "helper!"),
      { recursive: true },
    );
    await assert.rejects(
      loadAgentDir(root),
      /subagent directories "helper" and "helper!".*both slug to id "helper"/,
    );
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("agent id is the directory basename slugified", async () => {
  const { base, root } = await fixtureCopy("My Agent!!");
  try {
    const definition = await loadAgentDir(root);
    assert.equal(definition.id, "my-agent");
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("agent directories use canonical Agent Skills loading", async () => {
  const { base, root } = await fixtureCopy();
  try {
    const skillRoot = join(root, ".agents", "skills", "notes");
    await mkdir(skillRoot, { recursive: true });
    await writeFile(join(skillRoot, "SKILL.md"), [
      "---",
      "name: notes",
      "description: Working notes playbook.",
      "---",
      "",
      "Keep notes concise.",
      "",
    ].join("\n"));
    const definition = await loadAgentDir(root);
    const skills = definition.contexts.find((entry) => entry.id === "agent.skills");
    assert.match(skills.source, /- notes: Working notes playbook\./);
    assert.equal(definition.tools.some((entry) => entry.name === "load_skill"), true);
    const imported = await import(
      `${pathToFileURL(join(root, AGENT_DIR_ENTRY)).href}?cave=${Date.now()}`
    );
    assert.equal(agentDefinitionSHA256(imported.default), agentDefinitionSHA256(definition));
  } finally {
    await rm(base, { recursive: true, force: true });
  }
});

test("slugging: lowercase, invalid chars to -, collapse, trim; empty fails", () => {
  assert.equal(slugifyAgentDirId("Support-Bot"), "support-bot");
  assert.equal(slugifyAgentDirId("My  Agent!!"), "my-agent");
  assert.equal(slugifyAgentDirId("42_helper"), "42_helper");
  assert.throws(() => slugifyAgentDirId("!!!"), /not a valid agent id/);
  assert.throws(() => slugifyAgentDirId(""), /not a valid agent id/);
});
