// GENERATED by scripts/generate-agent-catalog.mjs — do not edit.
// Source: public/shared/provider-catalog/catalog/current.yaml, the repo's single pricing source of truth.
// CATALOG_SHA256 is the sha256 of those exact catalog bytes; the drift test in
// tests/catalog.drift.runtime.mjs fails until the generator is re-run.
//
// Included: every reviewed or routable USD row the catalog prices
// region-agnostically (region: global). Field mapping, catalog key
// -> TypeScript field:
//   input_per_million             -> inputPerMillion
//   output_per_million            -> outputPerMillion
//   cache_read_input_per_million  -> cacheReadPerMillion
//   cache_write_input_per_million -> cacheWritePerMillion
//   reasoning_output_per_million  -> reasoningPerMillion
// Optional null rates remain unknown. Costing and reservation fail closed when
// a corresponding observed or potentially used token class is nonzero; an
// explicit numeric 0 remains a reviewed free rate.
// Not modeled: 1h cache-write rates, batch discounts, cache storage, and
// long-context multipliers. These numbers are standard-tier public list-price
// subtotals, never an invoice.
export const CATALOG_SHA256 = "44f273c90cd7ab4707888fdf7ac5aea21d668e2204ef8a66683644e9151e1ce8";
export const CATALOG_SEMANTIC_SHA256 = "f9f74e012f52474ed3f0d4fdc40feef766cb035dd61eec1d97282946385942bb";
export const PRICE_PROVENANCE_SHA256 = "3712b1307ed08b02a1bb2c6ec4df1c3af14a6a3b619cba8b34f513f4bcc00035";

export interface CatalogPriceRates {
  inputPerMillion: number;
  outputPerMillion: number;
  cacheMode: "unknown" | "unsupported" | "explicit" | "implicit" | "affinity" | "automatic";
  cacheReadPerMillion: number | null;
  cacheWritePerMillion: number | null;
  reasoningPerMillion: number | null;
}

export interface CatalogRecurringUTCPriceWindow {
  startSecondUTC: number;
  endSecondUTC: number;
  price: CatalogPriceRates;
}

export interface CatalogRecurringUTCPricing {
  effectiveFrom: string;
  defaultPrice: CatalogPriceRates;
  windows: readonly CatalogRecurringUTCPriceWindow[];
}

export interface CatalogPrice extends CatalogPriceRates {
  recurringUTCPricing?: CatalogRecurringUTCPricing;
}

export type CatalogSupportState = "unknown" | "unsupported" | "supported";

export interface CatalogModelFacts {
  lifecycle: "discovered" | "reviewed" | "routable" | "retired";
  messagesAPI: CatalogSupportState;
  adaptiveThinking: CatalogSupportState;
  manualThinking: CatalogSupportState;
}

export interface CatalogUsage {
  provider: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  reasoningTokens: number;
}

const PRICES: Readonly<Record<string, CatalogPrice>> = Object.freeze({
  "anthropic/claude-haiku-4-5": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: 5,
  }),
  "anthropic/claude-haiku-4-5-20251001": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: 5,
  }),
  "anthropic/claude-opus-4-1": Object.freeze({
    inputPerMillion: 15,
    outputPerMillion: 75,
    cacheMode: "explicit",
    cacheReadPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    reasoningPerMillion: 75,
  }),
  "anthropic/claude-opus-4-8": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 25,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 25,
  }),
  "anthropic/claude-opus-5": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 25,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 25,
  }),
  "anthropic/claude-sonnet-4-5": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-4-5-20250929": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-4-6": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-5": Object.freeze({
    inputPerMillion: 2,
    outputPerMillion: 10,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.2,
    cacheWritePerMillion: 2.5,
    reasoningPerMillion: 10,
  }),
  "deepseek/deepseek-v4-flash": Object.freeze({
    inputPerMillion: 0.14,
    outputPerMillion: 0.28,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.0028,
    cacheWritePerMillion: null,
    reasoningPerMillion: 0.28,
    recurringUTCPricing: Object.freeze({
      effectiveFrom: "2026-08-16T16:00:00Z",
      defaultPrice: Object.freeze({
        inputPerMillion: 0.22,
        outputPerMillion: 0.66,
        cacheMode: "unsupported",
        cacheReadPerMillion: 0.007,
        cacheWritePerMillion: null,
        reasoningPerMillion: 0.66,
      }),
      windows: Object.freeze([
        Object.freeze({
          startSecondUTC: 3600,
          endSecondUTC: 14400,
          price: Object.freeze({
            inputPerMillion: 0.44,
            outputPerMillion: 1.32,
            cacheMode: "unsupported",
            cacheReadPerMillion: 0.014,
            cacheWritePerMillion: null,
            reasoningPerMillion: 1.32,
          }),
        }),
        Object.freeze({
          startSecondUTC: 21600,
          endSecondUTC: 36000,
          price: Object.freeze({
            inputPerMillion: 0.44,
            outputPerMillion: 1.32,
            cacheMode: "unsupported",
            cacheReadPerMillion: 0.014,
            cacheWritePerMillion: null,
            reasoningPerMillion: 1.32,
          }),
        }),
      ]),
    }),
  }),
  "deepseek/deepseek-v4-pro": Object.freeze({
    inputPerMillion: 0.435,
    outputPerMillion: 0.87,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.003625,
    cacheWritePerMillion: null,
    reasoningPerMillion: 0.87,
    recurringUTCPricing: Object.freeze({
      effectiveFrom: "2026-08-16T16:00:00Z",
      defaultPrice: Object.freeze({
        inputPerMillion: 0.66,
        outputPerMillion: 1.98,
        cacheMode: "unsupported",
        cacheReadPerMillion: 0.022,
        cacheWritePerMillion: null,
        reasoningPerMillion: 1.98,
      }),
      windows: Object.freeze([
        Object.freeze({
          startSecondUTC: 3600,
          endSecondUTC: 14400,
          price: Object.freeze({
            inputPerMillion: 1.32,
            outputPerMillion: 3.96,
            cacheMode: "unsupported",
            cacheReadPerMillion: 0.044,
            cacheWritePerMillion: null,
            reasoningPerMillion: 3.96,
          }),
        }),
        Object.freeze({
          startSecondUTC: 21600,
          endSecondUTC: 36000,
          price: Object.freeze({
            inputPerMillion: 1.32,
            outputPerMillion: 3.96,
            cacheMode: "unsupported",
            cacheReadPerMillion: 0.044,
            cacheWritePerMillion: null,
            reasoningPerMillion: 3.96,
          }),
        }),
      ]),
    }),
  }),
  "gemini/gemini-2.5-flash": Object.freeze({
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cacheMode: "implicit",
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: null,
    reasoningPerMillion: 2.5,
  }),
  "gemini/gemini-2.5-pro": Object.freeze({
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cacheMode: "implicit",
    cacheReadPerMillion: 0.125,
    cacheWritePerMillion: null,
    reasoningPerMillion: 10,
  }),
  "groq/llama-3.1-8b-instant": Object.freeze({
    inputPerMillion: 0.05,
    outputPerMillion: 0.08,
    cacheMode: "unsupported",
    cacheReadPerMillion: null,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "groq/llama-3.3-70b-versatile": Object.freeze({
    inputPerMillion: 0.59,
    outputPerMillion: 0.79,
    cacheMode: "unsupported",
    cacheReadPerMillion: null,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "groq/openai/gpt-oss-120b": Object.freeze({
    inputPerMillion: 0.15,
    outputPerMillion: 0.6,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: null,
    reasoningPerMillion: 0.6,
  }),
  "groq/openai/gpt-oss-20b": Object.freeze({
    inputPerMillion: 0.075,
    outputPerMillion: 0.3,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.037,
    cacheWritePerMillion: null,
    reasoningPerMillion: 0.3,
  }),
  "mistral/codestral-2508": Object.freeze({
    inputPerMillion: 0.3,
    outputPerMillion: 0.9,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "mistral/mistral-large-2512": Object.freeze({
    inputPerMillion: 0.5,
    outputPerMillion: 1.5,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.05,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "mistral/mistral-medium-3-5": Object.freeze({
    inputPerMillion: 1.5,
    outputPerMillion: 7.5,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.15,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "moonshot/kimi-k2.6": Object.freeze({
    inputPerMillion: 0.95,
    outputPerMillion: 4,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.16,
    cacheWritePerMillion: null,
    reasoningPerMillion: 4,
  }),
  "moonshot/kimi-k2.7-code": Object.freeze({
    inputPerMillion: 0.95,
    outputPerMillion: 4,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.19,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "moonshot/kimi-k3": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: null,
    reasoningPerMillion: 15,
  }),
  "openai/gpt-5.4-mini": Object.freeze({
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cacheMode: "affinity",
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: null,
    reasoningPerMillion: 4.5,
  }),
  "openai/gpt-5.4-mini-2026-03-17": Object.freeze({
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cacheMode: "affinity",
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: null,
    reasoningPerMillion: 4.5,
  }),
  "openai/gpt-5.4-nano": Object.freeze({
    inputPerMillion: 0.2,
    outputPerMillion: 1.25,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.02,
    cacheWritePerMillion: null,
    reasoningPerMillion: 1.25,
  }),
  "openai/gpt-5.4-nano-2026-03-17": Object.freeze({
    inputPerMillion: 0.2,
    outputPerMillion: 1.25,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.02,
    cacheWritePerMillion: null,
    reasoningPerMillion: 1.25,
  }),
  "openai/gpt-5.5": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheMode: "affinity",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: null,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.5-2026-04-23": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheMode: "affinity",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: null,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.6": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.6-sol": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheMode: "explicit",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 30,
  }),
  "openai/text-embedding-3-large": Object.freeze({
    inputPerMillion: 0.13,
    outputPerMillion: 0,
    cacheMode: "unknown",
    cacheReadPerMillion: null,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "openai/text-embedding-3-small": Object.freeze({
    inputPerMillion: 0.02,
    outputPerMillion: 0,
    cacheMode: "unknown",
    cacheReadPerMillion: null,
    cacheWritePerMillion: null,
    reasoningPerMillion: null,
  }),
  "vertex/claude-haiku-4-5@20251001": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: null,
  }),
  "vertex/claude-sonnet-4-6": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: null,
  }),
  "vertex/gemini-2.5-flash": Object.freeze({
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: null,
    reasoningPerMillion: 2.5,
  }),
  "vertex/gemini-2.5-pro": Object.freeze({
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cacheMode: "unknown",
    cacheReadPerMillion: 0.125,
    cacheWritePerMillion: null,
    reasoningPerMillion: 10,
  }),
  "xai/grok-4.3": Object.freeze({
    inputPerMillion: 1.25,
    outputPerMillion: 2.5,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.2,
    cacheWritePerMillion: null,
    reasoningPerMillion: 2.5,
  }),
  "xai/grok-4.5": Object.freeze({
    inputPerMillion: 2,
    outputPerMillion: 6,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: null,
    reasoningPerMillion: 6,
  }),
  "xai/grok-4.6": Object.freeze({
    inputPerMillion: 2,
    outputPerMillion: 6,
    cacheMode: "unsupported",
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: null,
    reasoningPerMillion: 6,
  }),
});

const MODELS: Readonly<Record<string, CatalogModelFacts>> = Object.freeze({
  "anthropic/claude-haiku-4-5": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unsupported",
    manualThinking: "supported",
  }),
  "anthropic/claude-haiku-4-5-20251001": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unsupported",
    manualThinking: "supported",
  }),
  "anthropic/claude-opus-4-1": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unsupported",
    manualThinking: "supported",
  }),
  "anthropic/claude-opus-4-8": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "supported",
    manualThinking: "unsupported",
  }),
  "anthropic/claude-opus-5": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "supported",
    manualThinking: "unsupported",
  }),
  "anthropic/claude-sonnet-4-5": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unsupported",
    manualThinking: "supported",
  }),
  "anthropic/claude-sonnet-4-5-20250929": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unsupported",
    manualThinking: "supported",
  }),
  "anthropic/claude-sonnet-4-6": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "supported",
    manualThinking: "supported",
  }),
  "anthropic/claude-sonnet-5": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "supported",
    manualThinking: "unsupported",
  }),
  "deepseek/deepseek-v4-flash": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "deepseek/deepseek-v4-pro": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "gemini/gemini-2.5-flash": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "gemini/gemini-2.5-pro": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "groq/llama-3.1-8b-instant": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "groq/llama-3.3-70b-versatile": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "groq/openai/gpt-oss-120b": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "groq/openai/gpt-oss-20b": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "mistral/codestral-2508": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "mistral/mistral-large-2512": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "mistral/mistral-medium-3-5": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "moonshot/kimi-k2.6": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "moonshot/kimi-k2.7-code": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "moonshot/kimi-k3": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.4-mini": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.4-mini-2026-03-17": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.4-nano": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.4-nano-2026-03-17": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.5": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.5-2026-04-23": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.6": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/gpt-5.6-sol": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/text-embedding-3-large": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "openai/text-embedding-3-small": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "vertex/claude-haiku-4-5@20251001": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "vertex/claude-sonnet-4-6": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "supported",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "vertex/gemini-2.5-flash": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "vertex/gemini-2.5-pro": Object.freeze({
    lifecycle: "reviewed",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "xai/grok-4.3": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "xai/grok-4.5": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
  "xai/grok-4.6": Object.freeze({
    lifecycle: "routable",
    messagesAPI: "unknown",
    adaptiveThinking: "unknown",
    manualThinking: "unknown",
  }),
});

/**
 * Provider cache-capability facts for the in-SDK cache planner, one entry per
 * runtime-eligible USD catalog row with a supported cache profile — every
 * region, keyed "provider/model@region", because cache facts are regional.
 * Rates ground write/read multipliers; null stays unknown, never guessed.
 */
export interface CatalogCacheProfile {
  id: string;
  mode: "explicit" | "implicit" | "affinity" | "automatic";
  attribution: string;
  minPrefixTokens: number;
  maxBreakpoints: number;
  ttlSeconds: number;
  rolling: boolean;
  routingKey: boolean;
  maxRpmPerKey: number;
  endpoints: readonly string[];
  inputPerMillion: number | null;
  cacheReadPerMillion: number | null;
  cacheWritePerMillion: number | null;
}

const CACHE_PROFILES: Readonly<Record<string, CatalogCacheProfile>> = Object.freeze({
  "anthropic/claude-haiku-4-5-20251001@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 4096,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 1,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
  }),
  "anthropic/claude-haiku-4-5@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 4096,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 1,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
  }),
  "anthropic/claude-opus-4-1@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 15,
    cacheReadPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
  }),
  "anthropic/claude-opus-4-8@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
  }),
  "anthropic/claude-opus-5@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
  }),
  "anthropic/claude-sonnet-4-5-20250929@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 3,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
  }),
  "anthropic/claude-sonnet-4-5@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 3,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
  }),
  "anthropic/claude-sonnet-4-6@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 3,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
  }),
  "anthropic/claude-sonnet-5@global": Object.freeze({
    id: "cave-cache-anthropic-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["v1/messages"]),
    inputPerMillion: 2,
    cacheReadPerMillion: 0.2,
    cacheWritePerMillion: 2.5,
  }),
  "bedrock/anthropic.claude-3-5-haiku-20241022-v1:0@us-east-1": Object.freeze({
    id: "cave-cache-bedrock-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 2048,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["converse", "converse-stream", "invoke", "invoke-with-response-stream"]),
    inputPerMillion: 0.8,
    cacheReadPerMillion: 0.08,
    cacheWritePerMillion: 1,
  }),
  "bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0@us-east-1": Object.freeze({
    id: "cave-cache-bedrock-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["converse", "converse-stream", "invoke", "invoke-with-response-stream"]),
    inputPerMillion: 6,
    cacheReadPerMillion: 0.6,
    cacheWritePerMillion: 7.5,
  }),
  "bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0@us-east-1": Object.freeze({
    id: "cave-cache-bedrock-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 4096,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["converse", "converse-stream", "invoke", "invoke-with-response-stream"]),
    inputPerMillion: 1,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
  }),
  "bedrock/global.anthropic.claude-opus-4-8@us-east-1": Object.freeze({
    id: "cave-cache-bedrock-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["converse", "converse-stream", "invoke", "invoke-with-response-stream"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
  }),
  "bedrock/global.anthropic.claude-sonnet-4-6@us-east-1": Object.freeze({
    id: "cave-cache-bedrock-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 300,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["converse", "converse-stream", "invoke", "invoke-with-response-stream"]),
    inputPerMillion: 3,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
  }),
  "gemini/gemini-2.5-flash@global": Object.freeze({
    id: "cave-cache-gemini-implicit-v1",
    mode: "implicit",
    attribution: "organic",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 0,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["generateContent"]),
    inputPerMillion: 0.3,
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: null,
  }),
  "gemini/gemini-2.5-pro@global": Object.freeze({
    id: "cave-cache-gemini-implicit-v1",
    mode: "implicit",
    attribution: "organic",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 0,
    rolling: true,
    routingKey: false,
    maxRpmPerKey: 0,
    endpoints: Object.freeze(["generateContent"]),
    inputPerMillion: 1.25,
    cacheReadPerMillion: 0.125,
    cacheWritePerMillion: null,
  }),
  "openai/gpt-5.4-mini-2026-03-17@global": Object.freeze({
    id: "cave-cache-openai-affinity-v1",
    mode: "affinity",
    attribution: "affinity",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 300,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 0.75,
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: null,
  }),
  "openai/gpt-5.4-mini@global": Object.freeze({
    id: "cave-cache-openai-affinity-v1",
    mode: "affinity",
    attribution: "affinity",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 300,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 0.75,
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: null,
  }),
  "openai/gpt-5.5-2026-04-23@global": Object.freeze({
    id: "cave-cache-openai-affinity-v1",
    mode: "affinity",
    attribution: "affinity",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 300,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: null,
  }),
  "openai/gpt-5.5@global": Object.freeze({
    id: "cave-cache-openai-affinity-v1",
    mode: "affinity",
    attribution: "affinity",
    minPrefixTokens: 2048,
    maxBreakpoints: 1,
    ttlSeconds: 300,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: null,
  }),
  "openai/gpt-5.6-sol@global": Object.freeze({
    id: "cave-cache-openai-explicit-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 1800,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
  }),
  "openai/gpt-5.6@global": Object.freeze({
    id: "cave-cache-openai-explicit-v1",
    mode: "explicit",
    attribution: "causal",
    minPrefixTokens: 1024,
    maxBreakpoints: 4,
    ttlSeconds: 1800,
    rolling: true,
    routingKey: true,
    maxRpmPerKey: 15,
    endpoints: Object.freeze(["v1/chat/completions", "v1/responses"]),
    inputPerMillion: 5,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
  }),
});

/** Cache profile lookup mirroring the Go engine: empty region means "global". */
export function catalogCacheProfile(
  provider: string,
  model: string,
  region?: string,
): CatalogCacheProfile | undefined {
  const where = (region ?? "").trim() === "" ? "global" : (region ?? "").trim();
  return CACHE_PROFILES[`${catalogProvider(provider.toLowerCase().trim())}/${model.trim()}@${where}`];
}

// Rows deliberately absent above. A regional rate is not a region-free
// rate, so these are omitted rather than borrowed; a run on one of these
// models prices as unpriced (honest zero) instead of plausibly wrong.
//   bedrock/anthropic.claude-3-5-haiku-20241022-v1:0 — priced per region only (us-east-1)
//   bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0 — priced per region only (us-east-1)
//   bedrock/global.amazon.nova-2-lite-v1:0 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-opus-4-8 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-sonnet-4-6 — priced per region only (us-east-1)
//   bedrock/mistral.ministral-3-8b-instruct — priced per region only (ap-northeast-1, ap-south-1, ap-southeast-2, eu-south-1, eu-west-1, eu-west-2, sa-east-1, us-east-1, us-east-2, us-west-2)
//   bedrock/mistral.mistral-large-3-675b-instruct — priced per region only (ap-northeast-1, ap-south-1, ap-southeast-2, sa-east-1, us-east-1, us-east-2, us-west-2)
//   bedrock/us.meta.llama4-maverick-17b-instruct-v1:0 — priced per region only (us-east-1)
//   bedrock/us.meta.llama4-scout-17b-instruct-v1:0 — priced per region only (us-east-1)

function catalogProvider(provider: string): string {
  // Runtime provider IDs come from Pi; catalog IDs name billing surfaces.
  if (provider === "google") return "gemini";
  if (provider === "google-vertex") return "vertex";
  return provider;
}

export function catalogRuntimeModel(
  provider: string,
  model: string,
): CatalogModelFacts | undefined {
  const facts = catalogModelFacts(provider, model);
  return catalogModelRuntimeEligible(facts) ? facts : undefined;
}

export function catalogModelFacts(
  provider: string,
  model: string,
): CatalogModelFacts | undefined {
  return MODELS[`${catalogProvider(provider)}/${model}`];
}

export function catalogModelRuntimeEligible(
  facts: CatalogModelFacts | undefined,
): facts is CatalogModelFacts {
  return facts !== undefined &&
    (facts.lifecycle === "reviewed" || facts.lifecycle === "routable") &&
    facts.messagesAPI === "supported";
}

export function catalogSearchCeiling(
  model: string,
  inputTokens: number,
  outputTokens: number,
  accountingAt?: Date,
): number | undefined {
  const slash = model.indexOf("/");
  const normalized = slash < 0
    ? model
    : `${catalogProvider(model.slice(0, slash))}/${model.slice(slash + 1)}`;
  const price = catalogPriceAt(PRICES[normalized], accountingAt);
  if (!price || !Number.isSafeInteger(inputTokens) || inputTokens < 0 ||
      !Number.isSafeInteger(outputTokens) || outputTokens < 0) {
    return undefined;
  }
  const cacheReadPossible = price.cacheMode !== "unsupported";
  const separatelyBilledCacheWritePossible =
    price.cacheMode === "unknown" || price.cacheMode === "explicit";
  if (inputTokens > 0) {
    if (cacheReadPossible && price.cacheReadPerMillion === null) return undefined;
    if (separatelyBilledCacheWritePossible && price.cacheWritePerMillion === null) return undefined;
  }
  if (outputTokens > 0 && price.reasoningPerMillion === null) return undefined;
  const inputRates = [price.inputPerMillion];
  if (inputTokens > 0 && cacheReadPossible) inputRates.push(price.cacheReadPerMillion!);
  if (inputTokens > 0 && separatelyBilledCacheWritePossible) {
    inputRates.push(price.cacheWritePerMillion!);
  }
  const worstInputRate = Math.max(...inputRates);
  const worstOutputRate = outputTokens === 0
    ? price.outputPerMillion
    : Math.max(price.outputPerMillion, price.reasoningPerMillion!);
  const usd = (inputTokens * worstInputRate + outputTokens * worstOutputRate) / 1_000_000;
  return Math.ceil(usd * 1e10) / 1e10;
}

export function catalogCostForPrice(
  price: CatalogPriceRates | undefined,
  usage: CatalogUsage,
): { priced: boolean; usd: number } {
  if (!price) return { priced: false, usd: 0 };
  if ((usage.cacheReadTokens > 0 && price.cacheReadPerMillion === null) ||
      (usage.cacheWriteTokens > 0 && price.cacheWritePerMillion === null) ||
      (usage.reasoningTokens > 0 && price.reasoningPerMillion === null)) {
    return { priced: false, usd: 0 };
  }
  // Pi normalizes input as uncached input. cacheRead/cacheWrite are disjoint
  // classes, while reasoning remains a subset of output.
  const billableInput = usage.inputTokens;
  const visibleOutput = usage.outputTokens - usage.reasoningTokens;
  if (
    billableInput < 0 ||
    visibleOutput < 0 ||
    Object.values(usage).some((value) => typeof value === "number" && (!Number.isSafeInteger(value) || value < 0))
  ) {
    return { priced: false, usd: 0 };
  }
  const usd = (
    billableInput * price.inputPerMillion +
    usage.cacheReadTokens * (price.cacheReadPerMillion ?? 0) +
    usage.cacheWriteTokens * (price.cacheWritePerMillion ?? 0) +
    visibleOutput * price.outputPerMillion +
    usage.reasoningTokens * (price.reasoningPerMillion ?? 0)
  ) / 1_000_000;
  return { priced: true, usd: Math.round((usd + Number.EPSILON) * 1e10) / 1e10 };
}

export function catalogPriceAt(
  price: CatalogPrice | undefined,
  accountingAt?: Date,
): CatalogPriceRates | undefined {
  return catalogPriceResolution(price, accountingAt)?.price;
}

function catalogPriceResolution(
  price: CatalogPrice | undefined,
  accountingAt?: Date,
): { price: CatalogPriceRates; epoch: string } | undefined {
  if (price === undefined) return undefined;
  if (price.recurringUTCPricing === undefined) return { price, epoch: "static" };
  if (accountingAt === undefined || Number.isNaN(accountingAt.getTime())) return undefined;
  const effective = Date.parse(price.recurringUTCPricing.effectiveFrom);
  if (!Number.isFinite(effective)) return undefined;
  if (accountingAt.getTime() < effective) return { price, epoch: "pre-effective" };
  const secondUTC = accountingAt.getUTCHours() * 3600 + accountingAt.getUTCMinutes() * 60 + accountingAt.getUTCSeconds();
  for (const window of price.recurringUTCPricing.windows) {
    if (secondUTC >= window.startSecondUTC && secondUTC < window.endSecondUTC) {
      return { price: window.price, epoch: `window:${window.startSecondUTC}-${window.endSecondUTC}` };
    }
  }
  return { price: price.recurringUTCPricing.defaultPrice, epoch: "default" };
}

/** Exact money-rate identity at a request time. It includes every nullable rate,
 * cache semantics, schedule epoch, and the generated price-provenance digest. */
export function catalogPriceFingerprint(
  provider: string,
  model: string,
  accountingAt?: Date,
): string | undefined {
  const resolution = catalogPriceResolution(
    PRICES[`${catalogProvider(provider)}/${model}`],
    accountingAt,
  );
  if (resolution === undefined) return undefined;
  const price = resolution.price;
  return JSON.stringify([
    PRICE_PROVENANCE_SHA256,
    resolution.epoch,
    price.inputPerMillion,
    price.outputPerMillion,
    price.cacheMode,
    price.cacheReadPerMillion,
    price.cacheWritePerMillion,
    price.reasoningPerMillion,
  ]);
}

export function catalogCost(
  usage: CatalogUsage,
  accountingAt?: Date,
): { priced: boolean; usd: number } {
  const provider = catalogProvider(usage.provider);
  return catalogCostForPrice(catalogPriceAt(PRICES[`${provider}/${usage.model}`], accountingAt), usage);
}
