import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { URL } from "node:url";
import { DomainError, idempotencyKey, identifier, validateReviewInput, type Principal, type VendorAnalyzer } from "./domain.js";
import { FileVendorStore } from "./store.js";

export function createVendorServer(options: { store: FileVendorStore; analyzer: VendorAnalyzer; credentials: ReadonlyMap<string, Principal>; logger?: (event: Record<string, unknown>) => void }) {
  const logger = options.logger ?? ((event: Record<string, unknown>) => process.stdout.write(`${JSON.stringify(event)}\n`));
  return createServer(async (request, response) => { const started = performance.now(); let status = 500; let errorCode: string | undefined; try { status = await route(request, response, options); } catch (error) { const failure = error instanceof DomainError ? error : new DomainError("internal_error", 500); status = failure.statusCode; errorCode = failure.code; send(response, status, { error: { code: failure.code } }); } finally { logger({ event: "request_complete", method: request.method, path: safePath(request.url), statusCode: status, durationMs: Math.round(performance.now() - started), ...(errorCode ? { errorCode } : {}) }); } });
}
async function route(request: IncomingMessage, response: ServerResponse, options: { store: FileVendorStore; analyzer: VendorAnalyzer; credentials: ReadonlyMap<string, Principal> }): Promise<number> {
  const url = new URL(request.url ?? "/", "http://vendor.local");
  if (request.method === "GET" && url.pathname === "/healthz") { send(response, 200, { status: "ok" }); return 200; }
  if (request.method === "GET" && url.pathname === "/readyz") { send(response, 200, await options.store.readiness()); return 200; }
  const principal = auth(request, options.credentials);
  if (request.method === "POST" && url.pathname === "/v1/reviews") { const result = await options.store.createReview(principal, idempotencyKey(request.headers["idempotency-key"]), validateReviewInput(await json(request))); response.setHeader("idempotency-replayed", String(result.replayed)); send(response, result.statusCode, result.body); return result.statusCode; }
  const getMatch = /^\/v1\/reviews\/([^/]+)$/.exec(url.pathname);
  if (request.method === "GET" && getMatch) { send(response, 200, await options.store.get(principal.tenantId, identifier(decode(getMatch[1]!)))); return 200; }
  const analyzeMatch = /^\/v1\/reviews\/([^/]+)\/analysis$/.exec(url.pathname);
  if (request.method === "POST" && analyzeMatch) { await empty(request); const id = identifier(decode(analyzeMatch[1]!)); const key = idempotencyKey(request.headers["idempotency-key"]); const reserved = await options.store.reserve(principal, key, id); if (reserved.replayed) { const replayStatus = reserved.statusCode ?? 200; response.setHeader("idempotency-replayed", "true"); send(response, replayStatus, reserved.body); return replayStatus; } try { const result = await options.analyzer({ runId: reserved.runId!, review: reserved.review!, vendor: reserved.vendor! }); const completed = await options.store.complete(principal, key, id, result); response.setHeader("idempotency-replayed", "false"); send(response, completed.statusCode, completed.body); return completed.statusCode; } catch (error) { const code = error instanceof DomainError ? error.code : "vendor_analysis_failed"; await options.store.fail(principal, key, id, code); throw new DomainError(code, error instanceof DomainError ? error.statusCode : 502); } }
  if (request.method === "GET" && url.pathname === "/v1/audit") { send(response, 200, { events: await options.store.audit(principal.tenantId) }); return 200; }
  throw new DomainError("route_not_found", 404);
}
function auth(request: IncomingMessage, credentials: ReadonlyMap<string, Principal>) { const header = request.headers.authorization; if (typeof header !== "string" || !header.startsWith("Bearer ")) throw new DomainError("unauthorized", 401); const token = Buffer.from(header.slice(7)); for (const [candidate, principal] of credentials) { const expected = Buffer.from(candidate); if (token.length === expected.length && timingSafeEqual(token, expected)) return principal; } throw new DomainError("unauthorized", 401); }
async function json(request: IncomingMessage) { if (!String(request.headers["content-type"] ?? "").toLowerCase().startsWith("application/json")) throw new DomainError("content_type_invalid", 415); const chunks: Buffer[] = []; let size = 0; for await (const chunk of request) { const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); size += bytes.length; if (size > 128 * 1024) throw new DomainError("request_body_too_large", 413); chunks.push(bytes); } try { return JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown; } catch { throw new DomainError("request_json_invalid", 400); } }
async function empty(request: IncomingMessage) { const body = await json(request); if (!body || typeof body !== "object" || Array.isArray(body) || Object.keys(body).length !== 0) throw new DomainError("analysis_input_invalid", 400); }
function send(response: ServerResponse, status: number, body: unknown) { if (response.headersSent) return; const bytes = Buffer.from(JSON.stringify(body)); response.statusCode = status; response.setHeader("content-type", "application/json; charset=utf-8"); response.setHeader("content-length", bytes.length); response.setHeader("cache-control", "no-store"); response.setHeader("x-content-type-options", "nosniff"); response.end(bytes); }
function decode(value: string) { try { return decodeURIComponent(value); } catch { throw new DomainError("identifier_invalid", 400); } }
function safePath(value?: string) { try { return new URL(value ?? "/", "http://vendor.local").pathname; } catch { return "invalid"; } }
export function parseCredentials(value: string): ReadonlyMap<string, Principal> { let parsed: unknown; try { parsed = JSON.parse(value); } catch { throw new Error("vendor_credentials_invalid"); } if (!Array.isArray(parsed) || parsed.length === 0) throw new Error("vendor_credentials_invalid"); const result = new Map<string, Principal>(); for (const value of parsed) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("vendor_credential_invalid"); const row = value as Record<string, unknown>; if (Object.keys(row).sort().join(",") !== "actorId,tenantId,token" || typeof row.token !== "string" || row.token.length < 24 || result.has(row.token)) throw new Error("vendor_credential_invalid"); result.set(row.token, { tenantId: identifier(row.tenantId), actorId: identifier(row.actorId) }); } return result; }
