import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { DomainError, emptyState, fingerprint, type AnalyzerResult, type Principal, type Review, type ReviewInput, type Vendor, type VendorState } from "./domain.js";

export class FileVendorStore {
  private state?: VendorState; private writeTail = Promise.resolve();
  constructor(private readonly path: string, private readonly clock = () => new Date()) {}
  async initialize(vendors: Vendor[]) { await this.serial(async () => { try { const state = JSON.parse(await readFile(this.path, "utf8")) as VendorState; if (state.schemaVersion !== 2 || !Array.isArray(state.vendors) || !Array.isArray(state.reviews) || !Array.isArray(state.audit) || state.idempotency === null || typeof state.idempotency !== "object") throw new Error("vendor_state_schema_unsupported"); this.state = state; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; this.state = emptyState(vendors); await this.persist(this.state); } }); }
  async readiness() { return this.read((state) => ({ status: "ready", schemaVersion: state.schemaVersion })); }
  async createReview(principal: Principal, key: string, input: ReviewInput) { return this.transaction((state) => { const operation = `${principal.tenantId}:review:create:${key}`; const hash = fingerprint(input); const replay = completed<Review>(state, operation, hash); if (replay) return replay; if (!state.vendors.some((vendor) => vendor.tenantId === principal.tenantId && vendor.id === input.vendorId)) throw new DomainError("vendor_not_found", 404); const now = this.clock().toISOString(); const review: Review = { id: `review_${randomUUID()}`, tenantId: principal.tenantId, ...input, status: "received", proposal: null, receipt: null, createdAt: now, updatedAt: now }; state.reviews.push(review); audit(state, principal, "review.created", "review", review.id, { vendorId: input.vendorId }, now); state.idempotency[operation] = { fingerprint: hash, state: "complete", statusCode: 201, body: review }; return { replayed: false, statusCode: 201, body: structuredClone(review) }; }); }
  async reserve(principal: Principal, key: string, id: string) { return this.transaction((state) => { const operation = `${principal.tenantId}:review:analyze:${key}`; const hash = fingerprint({ id }); const replay = completed<unknown>(state, operation, hash); if (replay) return { ...replay, review: undefined, vendor: undefined, runId: undefined }; const review = tenantReview(state, principal.tenantId, id); if (!review) throw new DomainError("review_not_found", 404); if (review.status !== "received" && review.status !== "review_failed") throw new DomainError("review_not_analyzable", 409); const vendor = state.vendors.find((item) => item.tenantId === principal.tenantId && item.id === review.vendorId); if (!vendor) throw new DomainError("vendor_not_found", 404); const now = this.clock().toISOString(); review.status = "reviewing"; review.updatedAt = now; state.idempotency[operation] = { fingerprint: hash, state: "running" }; audit(state, principal, "review.analysis_started", "review", id, {}, now); return { replayed: false, statusCode: undefined, body: undefined, review: structuredClone(review), vendor: structuredClone(vendor), runId: `vendor-${fingerprint({ tenant: principal.tenantId, id, key }).slice(0, 48)}` }; }); }
  async complete(principal: Principal, key: string, id: string, result: AnalyzerResult) { return this.transaction((state) => { const operation = `${principal.tenantId}:review:analyze:${key}`; const idem = state.idempotency[operation]; if (!idem || idem.state !== "running" || idem.fingerprint !== fingerprint({ id })) throw new DomainError("review_reservation_missing", 409); const review = tenantReview(state, principal.tenantId, id); if (!review || review.status !== "reviewing") throw new DomainError("review_not_running", 409); const now = this.clock().toISOString(); review.status = "proposal_ready"; review.proposal = structuredClone(result.proposal); review.receipt = structuredClone(result.receipt); review.updatedAt = now; audit(state, principal, "review.proposal_recorded", "review", id, { riskTier: result.proposal.riskTier, riskDisposition: result.proposal.riskDisposition, claimBasis: result.claimBasis, conditionCount: result.proposal.conditions.length }, now); const body = { review: structuredClone(review) }; Object.assign(idem, { state: "complete", statusCode: 200, body }); return { replayed: false, statusCode: 200, body }; }); }
  async fail(principal: Principal, key: string, id: string, code: string) { await this.transaction((state) => { const review = tenantReview(state, principal.tenantId, id); if (review?.status === "reviewing") { const now = this.clock().toISOString(); review.status = "review_failed"; review.updatedAt = now; audit(state, principal, "review.analysis_failed", "review", id, { code }, now); } delete state.idempotency[`${principal.tenantId}:review:analyze:${key}`]; }); }
  async get(tenant: string, id: string) { return this.read((state) => { const review = tenantReview(state, tenant, id); if (!review) throw new DomainError("review_not_found", 404); return structuredClone(review); }); }
  async audit(tenant: string) { return this.read((state) => structuredClone(state.audit.filter((event) => event.tenantId === tenant))); }
  private async read<T>(fn: (state: VendorState) => T) { let value!: T; await this.serial(async () => { value = fn(this.requireState()); }); return value; }
  private async transaction<T>(fn: (state: VendorState) => T) { let value!: T; await this.serial(async () => { const next = structuredClone(this.requireState()); value = fn(next); await this.persist(next); this.state = next; }); return value; }
  private async serial(fn: () => Promise<void>) { const prior = this.writeTail; let release!: () => void; this.writeTail = new Promise<void>((done) => { release = done; }); await prior; try { await fn(); } finally { release(); } }
  private requireState() { if (!this.state) throw new Error("vendor_store_not_initialized"); return this.state; }
  private async persist(state: VendorState) { await mkdir(dirname(this.path), { recursive: true, mode: 0o700 }); const temporary = `${this.path}.${process.pid}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(state, null, 2)}\n`, { mode: 0o600, flag: "wx" }); await rename(temporary, this.path); }
}
function tenantReview(state: VendorState, tenant: string, id: string) { return state.reviews.find((review) => review.tenantId === tenant && review.id === id); }
function completed<T>(state: VendorState, operation: string, hash: string) { const item = state.idempotency[operation]; if (!item) return undefined; if (item.fingerprint !== hash) throw new DomainError("idempotency_key_conflict", 409); if (item.state !== "complete" || item.statusCode === undefined) throw new DomainError("operation_in_progress", 409); return { replayed: true, statusCode: item.statusCode, body: structuredClone(item.body) as T }; }
function audit(state: VendorState, principal: Principal, action: string, resourceType: "review", resourceId: string, metadata: Record<string, string | number | boolean | null>, at: string) { state.sequence += 1; state.audit.push({ sequence: state.sequence, tenantId: principal.tenantId, actorId: principal.actorId, action, resourceType, resourceId, metadata, at }); }
