import { defineAdapterManifest } from "@caveman-ai/adapter-kit";

export const adapterManifest = defineAdapterManifest({
  schemaVersion: 2,
  id: "vercel-ai-sdk",
  packageName: "@caveman-ai/adapter-vercel-ai-sdk",
  adapterVersion: "0.1.0",
  upstream: { package: "ai", version: "7.0.84" },
  capabilities: {
    runLifecycle: "experimental",
    modelInterception: "experimental",
    contextTransformation: "experimental",
    toolObservation: "experimental",
    usageAccounting: "experimental",
    streaming: "experimental",
    abort: "experimental",
    replayAwareness: "unsupported",
    durableObservation: "unsupported",
    tracing: "unsupported",
    compilation: "unsupported",
  },
  lifecycle: {
    "run.started": "observe",
    "run.completed": "observe",
    "run.error": "unsupported",
    "model.requested": "intercept",
    "model.responded": "observe",
    "model.error": "observe",
    "tool.proposed": "unsupported",
    "tool.started": "observe",
    "tool.completed": "observe",
    "tool.error": "observe",
    "checkpoint.committed": "unsupported",
    "session.committed": "unsupported",
  },
  certifications: {},
});
