#!/usr/bin/env node
// Line-count ratchet for source files. A 8k-line module is where bugs hide and
// contributors bounce, so growth past the recorded budget has to be a deliberate,
// reviewed diff rather than an accident.
//
//   node scripts/size-budget.mjs            # check (CI)
//   node scripts/size-budget.mjs --update   # re-baseline, then review the diff
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const budgetPath = resolve(root, "size-budget.json");
/** Any source file without a recorded exception must stay under this. */
const DEFAULT_MAX_LINES = 1_000;

function sources(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === "dist" || entry.name[0] === ".") continue;
      sources(path, out);
    } else if (/\.(ts|mts|mjs|js)$/.test(entry.name) && !entry.name.endsWith(".d.ts")) {
      out.push(relative(root, path).split("\\").join("/"));
    }
  }
  return out;
}

/** Generated by an owning script; its size is not a contributor's to fix. */
const GENERATED = new Set(["packages/agent/src/catalog.ts"]);

const files = ["packages", "scripts"]
  .flatMap((dir) => sources(resolve(root, dir)))
  .filter((path) => !path.includes("/tests/") && !path.includes("/bench/") && !GENERATED.has(path))
  .sort();
const lines = new Map(
  files.map((path) => [path, readFileSync(resolve(root, path), "utf8").split("\n").length]),
);

const budget = JSON.parse(readFileSync(budgetPath, "utf8"));
if (process.argv.includes("--update")) {
  // The recorded default wins over the constant so a deliberate edit to
  // size-budget.json survives a re-baseline.
  const defaultMaxLines = budget.defaultMaxLines ?? DEFAULT_MAX_LINES;
  const exceptions = Object.fromEntries(
    files.filter((path) => lines.get(path) > defaultMaxLines).map((path) => [path, lines.get(path)]),
  );
  writeFileSync(budgetPath, `${JSON.stringify({ defaultMaxLines, exceptions }, null, 2)}\n`);
  process.stdout.write(`size-budget: re-baselined ${Object.keys(exceptions).length} exception(s)\n`);
  process.exit(0);
}

// Growth is the only failure. Shrinking a file below its exception, or deleting
// it, must never fail the build — the ratchet exists to stop files getting
// bigger, and a check that also punishes progress just teaches people to run
// `--update` reflexively. Stale generous caps get tightened on the next
// `--update`, which re-derives every exception from the current tree.
const failures = [];
for (const [path, count] of lines) {
  const cap = budget.exceptions[path] ?? budget.defaultMaxLines;
  if (count > cap) failures.push(`${path}: ${count} lines exceeds budget ${cap}`);
}

if (failures.length > 0) {
  for (const line of failures) process.stderr.write(`size-budget: ${line}\n`);
  process.stderr.write("size-budget: split the file, or run `node scripts/size-budget.mjs --update` and justify it in review\n");
  process.exit(1);
}
process.stdout.write(`size-budget: ok (${lines.size} files, ${Object.keys(budget.exceptions).length} exceptions)\n`);
